### ISSUE TITLE
Idea and Idea-CE both require Java 1.6 out of the box but Java 1.6 is end-of-lifed

### ISSUE THREAD

**Issue by codeword** [pivotal-sprout/sprout-jetbrains-editors#1]
Most new workstations will have either Java 7 (1.7) or 8 (1.8) installed, neither of these will work with a fresh install of Idea (either Ultimate or CE).  Rubymine is setup to run with any Java > 1.6 so will work fine with 7 or 8.

looking at this really stale article https://intellij-support.jetbrains.com/entries/23455956-Selecting-the-JDK-version-the-IDE-will-run-under, They have a way to change the JVMVersion entry in the (/[App Root]/Contents/Info.plist)

if you change the value from 1.6\* to 1.6+ it will work with any version of java after 1.6

I think these installer recipies should also modify this plilst after installation.

**Comment by LukeWinikates** [comment]
Is it easy to reproduce this? (e.g. does IntelliJ fail to install properly on a fresh Yosemite iMac?) 

Looking at the linked article and at another relevant (old) article on JetBrains' KB (https://intellij-support.jetbrains.com/entries/27854363-IDE-doesn-t-start-after-updating-to-Mac-OS-Yosemite-or-Mavericks), JetBrains seem to encourage folks to use Java 6. They also list Java 6 as a system requirement on https://www.jetbrains.com/idea/download/

The commentary from JetBrains makes running IntelliJ on Java 7 or 8 sound like a rocky experience. Are you running IntelliJ stably and happily on 7 (or 8?) Should we be installing Java 7 or 8 as a prerequisite to this recipe? 

Or should we be installing Apple's crusty old Java 6 as a prerequisite for IntelliJ? My guess is that installing Java 6 is what we've done on Labs' workstations, since we've been on Mavericks for a while now.

**Comment by codeword** [comment]
I have been working on a patch for this.  I have seen a lot of successful
installs the jetbrains editors using java 7 & 8,  I think it runs a lot
faster, but may be a bit less stable.  The reality is that teams need to
use a later java for various reasons and these days it is hard/impossible
to install java 6.  Tweaking the JVMVersion key in the Info.plist from 1.6*
to 1.6+ causes the editor to use any version of the java installed as long
as it is greater or equal to java 6.

To answer you question directly, I haven't actually tested installing the
editor with no java installed, I'm not sure if it will promt to install
java or just not work, but when you say 'brew cask install java' it will
install java 8.  If you then install one of the IDE's and try to launch it,
it simply dies.  You have to launch it from the command line to see the
error which has something to do with not finding a java runtime.  If you
then tweak the plist value, it launches fine.

Luke, if you created the lwrp for the sprout-jetbrains-eidtors, I may want
to pick you brain about creating one to do this tweaking, or maybe we can
pair after hours on a solution (what time zone are you in?)

-Jonathan
